name: split_wise
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  google_sign_in: ^6.0.0
  video_player:
  cached_network_image:
  flutter_riverpod:
  image_picker:
  supabase_flutter:
  shared_preferences:
  slider_button: ^2.1.0
  permission_handler:
  lottie:
  intl:
  google_nav_bar:
  curved_navigation_bar:
  animate_do:         # For smooth animations
  flutter_animate: ^4.5.0      # Additional animation capabilities
  flutter_neumorphic: ^3.2.0
  rtf_textfield: ^1.0.0 # For neumorphic design elements
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  firebase_messaging:
  flutter_local_notifications:
  flutter_foreground_task:
  path_provider:
  pdf:
  http:
  googleapis_auth:
  flutter_spinkit: ^5.2.1
  url_launcher:
  device_preview: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/logo/g1.png
    - assets/animation/56qRH8Xl3ih8DWE25i.mp4
    - assets/fonts/
    - assets/animation/45.json
    - assets/split-wise-891b7-firebase-adminsdk-fbsvc-48c6733945.json
